# Generated by Django 4.1.3 on 2022-11-08 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_tumbled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeding',
            options={'ordering': ['-date']},
        ),
    ]
