# Generated by Django 4.1.3 on 2022-11-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_feeding_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tumbled',
            name='brand',
            field=models.CharField(default='N', max_length=50),
        ),
    ]
