# Generated by Django 4.1.3 on 2022-11-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_tumbled_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Chonk', max_length=50)),
                ('size', models.IntegerField()),
                ('species', models.CharField(default='BullFrog', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Tumbled',
        ),
    ]
