# Generated by Django 4.1.3 on 2022-11-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_rock_frogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='meal',
            field=models.CharField(choices=[('MR', 'Mushies'), ('MO', 'Moss'), ('L', 'Lichen')], default='MO', max_length=2),
        ),
    ]
