# Generated by Django 4.1.3 on 2022-11-10 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0010_alter_feeding_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rock',
            name='hardness',
        ),
        migrations.AddField(
            model_name='rock',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
